### ISSUE TITLE
Add other applications

### ISSUE THREAD

**Issue by jagalindo** [phoenixbyrd/App-Installer#1]
I've been trying to install vscode with lo luck on this enviroment (updated yesterday)

Also, I'm trying to figure it out how to manage mimetipes when the firefox explorer call an all that is within the prrot enviroment

**Comment by jagalindo** [comment]
Figure it Outlook that for code you can start it with the -no-sandbox option

**Comment by phoenixbyrd** [comment]
Sorry, camping right now. This is still being slowly worked on. VS Code has been added. Will add other stuff over time as I come across them. Working out how to make it update everything when it's ran by the user first.

**Comment by phoenixbyrd** [comment]
OK, got the script to update so each time a user runs it it will show any new apps added. Will have this install with the termux_xfce script too.
